### ISSUE TITLE
Создать контроллер пользователя

### ISSUE THREAD

**Issue by xandrck** [xandrck/oblivion#13]
users_controller
реализовать функционал:
 редактирования пользователя (только самого себя)
 просмотр списка пользователей (на будующее для админа)

**Comment by RoRElessar** [comment]
Для реализации редактирования пользователя, я так поинмаю, нужно создавать миграцию, что бы она в базу данных внесла таблицу?

**Comment by xandrck** [comment]
нет, в базе уже всё есть (в базе нужны поля, которые потом можно будет редактировать, в данном случае это fullname)
